### ISSUE TITLE
Terraform 0.13 support not available on official registry

### ISSUE THREAD

**Issue by van-vliet** [trussworks/terraform-aws-acm-cert#48]
When using the latest version (3.0.0) from the [terraform registry](https://registry.terraform.io/modules/trussworks/acm-cert/aws/3.0.0), the changes introduced in #47 are not included.

Can you push the updated version to the registry or release a new version?

**Comment by ralren** [comment]
That's strange. I created a new release (v3.0.1) and that seems to have fixed this mess. Thank you for bringing this to our attention.
